Memory Writes are performed in third stage
gaph-pucrs/PUC-RS5 pull request #10
Opened 2023-06-14 17:09 UTC by Willian-Nunes

2023-06-14 17:49 UTC, Willian-Nunes commented
![image](https://github.com/gaph-pucrs/PUC-RS5/assets/57405067/32d09ecb-a279-4246-8a0e-d0bd434a7b7e)
![image](https://github.com/gaph-pucrs/PUC-RS5/assets/57405067/7b091f34-8376-4fdd-bfab-e0da08bfb49a)

2023-06-15 13:53 UTC, aedalzotto commented
> ![image](https://user-images.githubusercontent.com/57405067/245889309-32d09ecb-a279-4246-8a0e-d0bd434a7b7e.png) ![image](https://user-images.githubusercontent.com/57405067/245889429-7b091f34-8376-4fdd-bfab-e0da08bfb49a.png)

Is this with or without MMU?

2023-06-15 13:55 UTC, aedalzotto commented
@carol045 Please test this branch with coremark and berkeley COE before we approve.

2023-06-15 13:59 UTC, Willian-Nunes commented
> > ![image](https://user-images.githubusercontent.com/57405067/245889309-32d09ecb-a279-4246-8a0e-d0bd434a7b7e.png) ![image](https://user-images.githubusercontent.com/57405067/245889429-7b091f34-8376-4fdd-bfab-e0da08bfb49a.png)
> 
> Is this with or without MMU?

With

2023-06-28 21:12 UTC, aedalzotto requested changes
Just remove temporary and binary files, commit the removal, add them to .gitignore and it's good to go!

2023-06-28 21:12 UTC, aedalzotto commented on proto/privileged/privileged.srcs/sources_1/ip/.Xil/.BRAM.xcix.lock
Add `**/.Xil` to .gitignore

2023-06-28 21:12 UTC, aedalzotto commented on proto/privileged/privileged.srcs/sources_1/ip/BRAM.xcix
Add `*.xcix` to .gitignore

2023-06-28 21:12 UTC, aedalzotto commented on proto/privileged/privileged.srcs/sources_1/ip/.Xil/.BRAM.xcix.lock
First commit this folder removal

2023-06-28 21:12 UTC, aedalzotto commented on proto/privileged/privileged.srcs/sources_1/ip/BRAM.xcix
First commit this file removal

2023-06-29 14:39 UTC, aedalzotto approved these changes

2023-06-29 14:39 UTC, merged